server.port=8080
USERS_AZURE_URL=${USERS_AZURE_URL:https://b6funciontex.azurewebsites.net}
LOANS_AZURE_URL=${LOANS_AZURE_URL:https://b6funciontex2.azurewebsites.net}
AUTHORS_AZURE_URL=${AUTHORS_AZURE_URL:https://b6funciontex3.azurewebsites.net}
BOOKS_AZURE_URL=${BOOKS_AZURE_URL:https://b6funciontex4.azurewebsites.net}
spring.main.banner-mode=off
